"""Turn an approved plan into a followable DIY roadmap."""

from dataclasses import dataclass

from .planning_contract import PlanSummary, PlanningResponse


@dataclass(frozen=True)
class DiyRoadmap:
    plan_id: str
    filename: str
    markdown: str


def slug(text: str) -> str:
    cleaned = "".join(ch.lower() if ch.isalnum() else "-" for ch in text.strip())
    parts = [part for part in cleaned.split("-") if part]
    return "-".join(parts[:8]) or "caos-idea"


def render_roadmap(response: PlanningResponse, plan_id: str | None = None) -> DiyRoadmap:
    selected = _select_plan(response, plan_id)
    filename = f"{slug(response.idea)}-diy.md"
    lines = [
        f"# DIY roadmap: {response.idea}",
        "",
        f"CAOS plan: **{selected.label}** (`{selected.plan_id}`)",
        "",
        "## What CAOS understood",
        response.blueprint_summary or "No blueprint summary.",
        "",
        "## Cost honesty",
        f"- Estimated monetary cost: ${selected.monetary_cost:.2f}",
        f"- Estimated execution time: {selected.execution_minutes:.0f} minutes",
        f"- Estimated quota wait: {selected.quota_wait_minutes:.0f} minutes",
        "- These numbers are estimates from the dated resource registry, not a live provider bill.",
        "- Actual cost appears only after a BUILD run records ExecutionUsage.",
        "",
        "## Assumptions",
    ]
    assumptions = response.assumptions or (
        "Free quota is taken from the CAOS registry, not a live provider probe.",
        "Cost is estimated until BUILD records actual usage.",
    )
    lines.extend(f"- {item}" for item in assumptions)
    lines.extend(["", "## Steps"])
    for index, step in enumerate(_steps_for(response, selected), start=1):
        lines.append(f"{index}. {step}")
    lines.extend([
        "",
        "## Done when",
        "- The core flow described in the idea can be demonstrated locally.",
        "- Secrets stay out of source control.",
        "- You know which steps used free quota and which would require paid spillover.",
        "",
        "## If a free limit runs out",
        "Stop. Record what is finished. Resume on another free channel or accept the itemized paid spillover from the Lowest Practical Cost plan.",
        "",
        "Generated by CAOS. This is a roadmap, not a guarantee of globally lowest cost.",
    ])
    return DiyRoadmap(selected.plan_id, filename, "\n".join(lines) + "\n")


def _select_plan(response: PlanningResponse, plan_id: str | None) -> PlanSummary:
    wanted = plan_id or response.recommendation
    for plan in response.plans:
        if plan.plan_id == wanted:
            return plan
    if response.plans:
        return response.plans[0]
    raise ValueError("Planning response has no plans to document")


def _steps_for(response: PlanningResponse, plan: PlanSummary) -> list[str]:
    path = plan.critical_path or ()
    steps = [
        "Write the outcome in one sentence and list what done looks like.",
        "Create a local folder and a git repo. Keep this DIY file next to the code.",
        "Prefer free local tools first (editor, git, pytest, the CAOS deterministic workspace).",
    ]
    if path:
        steps.append("Work the critical path in order: " + " -> ".join(path) + ".")
    steps.extend([
        f"Implement the {plan.label} route only. Do not add paid APIs until a free option is exhausted.",
        "Add one automated check for the main user action.",
        "Run the check. If it fails, fix the smallest thing that explains the failure.",
        "Write down estimated vs actual cost. For a local DIY run, actual should stay $0.",
    ])
    if "DIY" in response.next_actions:
        steps.append("Keep a short handoff note so another person or agent can continue without rereading the whole chat.")
    return steps
